traindata: features/hdf5/asv15/spec/train.h5
trainlabel: data/filelists/asv15/train.tsv
testdata: [features/hdf5/asv15/spec/eval.h5] #Multiple testdata is also allowed
testlabel: [data/filelists/asv15/eval.tsv]
optimizer: Adam
optimizer_args:
  lr: 0.004
transforms: [] # no transformations
batch_size: 64
num_workers: 3
epochs: 100
# BCELoss has no args, otherwise FocalLoss can have 'alpha' and 'gamma'
loss: CrossEntropyLoss
loss_args: {}
model: LightCNN
model_args: {}
sampler: {} # No extra sampling strategy
outputpath: experiments/asv15/

