traindata: features/hdf5/btas16/spec/train.h5
trainlabel: data/filelists/btas16/train.tsv
testdata: [features/hdf5/btas16/spec/eval.h5] #Multiple testdata is also allowed
testlabel: [data/filelists/btas16/eval.tsv]
optimizer: Adam
optimizer_args:
  lr: 0.004
transforms: [] # no transformations
batch_size: 16 # Some utterances are rather long
num_workers: 3
epochs: 100
# BCELoss has no args, otherwise FocalLoss can have 'alpha' and 'gamma'
loss: CrossEntropyLoss
loss_args: {}
model: LightCNN
model_args: {}
sampler: {} # No extra sampling strategy
shuffle: True
outputpath: experiments/btas16/

