traindata: features/hdf5/FoR/lms/train.h5
trainlabel: data/filelists/FoR/train.csv
testdata: [data/hdf5/FoR/eval.h5] #Multiple testdata is also allowed
testlabel: [data/hdf5/FoR/eval.csv]
optimizer: Adam
optimizer_args:
  lr: 0.004
transforms: [] # no transformations
dataloader_args:
  batch_size: 64
  num_workers: 3
epochs: 100
# BCELoss has no args, otherwise FocalLoss can have 'alpha' and 'gamma'
loss: CrossEntropyLoss
loss_args: {}
model: LightCNN
model_args: {}
sampler: {} # No extra sampling strategy
shuffle: True
outputpath: experiments/FoR/
