traindata: features/hdf5/FoR_norm/spec/train.h5
trainlabel: data/filelists/FoR/for-norm_train.tsv
testdata: [features/hdf5/FoR_norm/spec/eval.h5] #Multiple testdata is also allowed
testlabel: [data/filelists/FoR/for-norm_eval.tsv]
optimizer: Adam
optimizer_args:
  lr: 0.004
transforms: [] # no transformations
batch_size: 16
num_workers: 3
epochs: 100
# BCELoss has no args, otherwise FocalLoss can have 'alpha' and 'gamma'
loss: CrossEntropyLoss
loss_args: {}
model: LightCNN
model_args: {}
sampler: {} # No extra sampling strategy
outputpath: experiments/FoR/
